- app/gateway/proxy.py
GitLab expects filepaths to be URL-encoded when requesting repository files. Fix the automatic unencoding done by flask.
> Fix urlencoded filepaths as resource identifiers in request urls

- Makefile
- app/gateway/proxy.py
- app/helpers/gitlab_user_utils.py
- app/tests/test_proxy.py
Address the problems found during deployment on testing.datascience.ch.
> Match gitlab users

- Makefile
- run-telepresence.sh
Make dev setting easily accessible through `make dev`.
> Use telepresence for local development

- app/gateway/proxy.py
> Abort on error

- app/auth/web.py
The route for refreshing tokens is has been implemented a while ago...
> Remove outdated (and misleading) comment

- Dockerfile
- Makefile
- Pipfile
- Pipfile.lock
- app/__init__.py
- app/auth/web.py
- app/gateway/__init__.py
- app/gateway/proxy.py
- app/helpers/gitlab_client.py
- app/helpers/gitlab_parsers.py
- app/processors/__init__.py
- app/processors/base_processor.py
- app/processors/gitlab_processor.py
- app/processors/service_processor.py
- app/tests/test_config.py
- app/tests/test_proxy.py
- run-telepresence.sh
- run.py
tests are broken, it seems it is not possible to use responses and asyncio simultaneously
> Replace Flask by Quart

- .travis.yml
- Dockerfile
- run-telepresence.sh
- run.py
Bring file watching / hot reloading back to the development setup.
> File watching / reloading for quart dev server

- helm-chart/renku-gateway/templates/deployment.yaml
- helm-chart/renku-gateway/templates/secret.yaml
> Use k8s secrets

- app/processors/base_processor.py
- helm-chart/renku-gateway/templates/deployment.yaml
- run-telepresence.sh
Remove a header from the request before forwarding which can cause problems related to ssl.
> Fix request headers before forwarding

- .travis.yml
- Dockerfile
- Pipfile
- Pipfile.lock
- app/processors/__init__.py
- app/processors/base_processor.py
- app/processors/gitlab_processor.py
- app/tests/test_proxy.py
Use asynchronous (aiohttp) requests. Note that some of the requests made during login are still synchronous. However, for communication with the gitlab or jupyterhub API, this greatly improves the performance of the gateway.
> Fix synchronous requests

- app/blueprints/graph.py
closes #87 
see https://rok.dev.renku.ch/api/graph/rokroskar/zurich-bikes-data/lineage/85a49605d9a579221841720540ec6248c6775f49
> fix broken sparql query

- run-telepresence.sh
- Fix path to quart app
- Adapt to our dev cluster setup
- Use `inject-tcp` method per default only on non-linux machines
> Fix and update the `run-telpresence.sh` script

- app/blueprints/graph.py
Feel free to improve, my Python knowledge is still pretty basic.
I hope the workaround to remove useless final nodes is fine, but it would be good to test in different scenarios. I will soon publish a test version with working UI
> Remove obsolete nodes from graph

- app/blueprints/graph.py
https://graphpreview.dev.renku.ch
> remove unuseful top nodes containing renku commands

- helm-chart/renku-gateway/templates/configmap.yaml
See `Regex Syntax` described here: https://docs.traefik.io/v2.0/routing/routers/#rule
> Fix traefik config for webhook service

- app/__init__.py
Log more information about the public key retrieval from keycloak.
> Add more logging on startup

- app/auth/gitlab_auth.py
- app/auth/web.py
Both, keycloak and gitlab offer an endpoint to query the relevant URLs for their role as openId connect provider. We make sure that these enpoints are queried repetedly until the two services are actually up.
Closes #123.
> Fix infinite redirection on login

- Pipfile
- Pipfile.lock
- app/blueprints/graph.py
- helm-chart/chartpress.yaml
- helm-chart/renku-gateway/values.yaml
> Jena basic auth

- app/__init__.py
- app/auth/core_auth.py
- app/auth/renku_auth.py
- helm-chart/renku-gateway/Chart.yaml
- helm-chart/renku-gateway/templates/configmap.yaml
> feat: add core service routing

- .travis.yml
- .travis/travis-deploy.sh
- .travis/travis-functions.sh
Note that the travis CLI did some auto-modifications to .travis-ci.yaml.
> build: automatically update renku-gateway dependency in renku

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
* Update the `CHANGES.rst` file to be coherent with the release notes.
* Bump chart version to `0.8.1`
> chore: update changes and bump chart version

- Dockerfile
- Pipfile
- Pipfile.lock
Also bump pip to 20.1.1 in the Dockerfile. This is necessary for installing gevent.
> Add missing gunicorn its dependencies

- Pipfile
- Pipfile.lock
This was forgotten when moving back to Flask.
> Remove unused hypercorn package

- helm-chart/renku-gateway/requirements.lock
- helm-chart/renku-gateway/requirements.yaml
See https://github.com/SwissDataScienceCenter/renku/issues/1271 for context.
> Bump redis chart version

- .gitignore
- .travis/travis-deploy.sh
Adds the bitnami helm repository.
> fix travis deploy

- .dockerignore
- Dockerfile
- Pipfile
- Pipfile.lock
- app/__init__.py
- helm-chart/renku-gateway/templates/deployment.yaml
This adds sentry to the gateway-auth flask app. 
Seems to work 🎉 see https://sentry.dev.renku.ch/share/issue/633a29be1d7d416e921610e3d32cf929/
> chore: add sentry

- helm-chart/renku-gateway/values.yaml
Adds missing default null values to the values file for sentry.
> chore(helm): add sentry to values file

- Pipfile.lock
This PR combines several dependabot updates.
> Dependabot updates

- .github/workflows/ci.yml
> chore: update deprecated github actions

- .github/workflows/acceptance-tests.yaml
Adds acceptance test action
/deploy
> chore: add acceptance test action

- Pipfile.lock
This includes a vulnerability fix.
/deploy
> chore: update a bunch of dependencies

- Pipfile.lock
- app/auth/cli_auth.py
- app/auth/jupyterhub_auth.py
- app/auth/web.py
> chore: a bunch of dependency upgrades

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
guess our action wants a comment here
> chore: prep 0.9.5 release

- .github/workflows/ci.yml
> chore: fix chart publishing

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
> Prep 0.10.0 release

- .github/workflows/acceptance-tests.yaml
- .github/workflows/ci.yml
> chore: bump actions version

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
/deploy renku=448c938d4d4a4b263857fba8ff2d402f72ad9fba
> chore: prepare 0.10.2 release

- .github/workflows/ci.yml
> chore: use org github secret everywhere

- app/__init__.py
re #SwissDataScienceCenter/renku-ui#1521
/deploy
> fix: remove path constraint on anon-id cookie

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
> chore: prepare 0.11.0 release

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
The only notable change is the ability to use custom CA certificates.
> chore: prepare 0.12.0 release

- .github/workflows/codeql-analysis.yml
> chore: set up github codeql workflow

- Pipfile.lock
> chore: rebuild lockfile from scratch

- app/__init__.py
- helm-chart/renku-gateway/templates/deployment.yaml
- helm-chart/renku-gateway/values.yaml
Align sentry values with the other renku repositories.
Reference: https://swiss-data-science.slack.com/archives/G67N59QL8/p1643901194490749
/deploy extra-values=gateway.sentry.enabled=true,gateway.sentry.environment=renku-gateway-sentry-update
> build: update sentry values

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
> chore: prepare release 0.12.3

- app/__init__.py
- app/config.py
- helm-chart/renku-gateway/templates/_helpers.tpl
- helm-chart/renku-gateway/templates/deployment.yaml
- helm-chart/renku-gateway/values.yaml
/deploy renku=fix-global-redis-values renku-ui=use-global-redis #persist
> fix(chart)!: modify values for global redis

- .github/workflows/acceptance-tests.yaml
- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
/deploy extra-values=gateway.allowOrigin="https://example.com" #persist
> Add middlewares CORS.

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
empty description (https://github.com/SwissDataScienceCenter/renku-actions/issues/7)
> chore(release) Prepare 0.13.1.

- Dockerfile
- helm-chart/renku-gateway/templates/deployment.yaml
- helm-chart/renku-gateway/values.yaml
closes https://github.com/swissdatasciencecenter/renku-notebooks/issues/1002
/deploy renku=ableuler-patch-1 #persist
> chore: run as non-root

- app/__init__.py
- app/auth/notebook_auth.py
Anon-id cookies will be set by the UI server
/deploy renku-ui=1601-anon-id #persist
> feat: remove anon-id cookies creation

- Dockerfile
- app/__init__.py
- app/auth/notebook_auth.py
- app/auth/renku_auth.py
- app/auth/utils.py
> fix(app): re-initialize keycloak client if needed

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
> chore: prep 0.15.0 release

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
> chore: prep 0.16.0 release

- helm-chart/renku-gateway/templates/deployment.yaml
- helm-chart/renku-gateway/values.yaml
addresses https://github.com/SwissDataScienceCenter/renku/issues/2683 for the gateway
> chore: prevent service account from being automounted

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
> chore: prepare release 0.17.0

- .gitignore
- app/__init__.py
- app/auth/cli_auth.py
Fixes vulnerabilities reported here: https://app.snyk.io/org/renku/project/8d4abcfc-8c35-4fb1-b5ae-265a4152c7c0
> fix(app): snyk vulnerabilities

- app/auth/web.py
> fix(app): do not remove redis clients on logout

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
> chore: prep 0.18.0 release

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
> chore: prep 0.18.1 release

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
> chore: prep 0.19.1 release

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
> chore: prep 0.19.2 release

- cmd/revproxy/config.go
- cmd/revproxy/main.go
- helm-chart/renku-gateway/templates/deployment-revproxy.yaml
- helm-chart/renku-gateway/values.yaml
Adds the required changes for the compute resource access control service.
> chore: add crc service

- app/auth/web.py
/deploy #persist renku=master
Fixes the logout for the update of keycloak.
The reason that this is required is because of this: https://www.keycloak.org/docs/20.0.5/upgrading/index.html#openid-connect-logout
Namely after keycloak version 18 logging out can be done fully only after the user clicks on a confirmation page that is shown by keycloak. So prior to version 18 going to something like https://dev.renku.ch/auth/realms/Renku/protocol/openid-connect/logout would simply log you out from Keycloak and destroy any Keycloak cookies in the browser. But after version 18 going to that page renders a page that asks the user the confirm the logout request. And only after the request is confirm is the keycloak session and cookies fully destroyed.
The only way to bypass the confirmation page is …
> fix: logout with new keycloak version

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
> chore: prep 0.20.1 release

- .github/workflows/ci.yml
- Dockerfile.revproxy
- cmd/revproxy/config.go
- cmd/revproxy/main.go
- cmd/revproxy/main_test.go
- cmd/revproxy/proxies.go
- go.mod
- go.sum
- helm-chart/renku-gateway/templates/_helpers.tpl
- helm-chart/renku-gateway/templates/deployment-revproxy.yaml
- helm-chart/renku-gateway/templates/role.yaml
- helm-chart/renku-gateway/templates/rolebinding.yaml
- helm-chart/renku-gateway/templates/serviceaccount.yaml
- helm-chart/renku-gateway/values.yaml
- internal/stickysessions/main.go
- internal/stickysessions/main_test.go
merge with https://github.com/SwissDataScienceCenter/renku-python/pull/3178
> feat: core-service sticky sessions

- CHANGELOG.md
- cmd/revproxy/config.go
- cmd/revproxy/main.go
- cmd/revproxy/main_test.go
- cmd/revproxy/middlewares.go
- cmd/revproxy/proxies.go
- helm-chart/renku-gateway/Chart.yaml
- helm-chart/renku-gateway/templates/_helpers.tpl
- helm-chart/renku-gateway/templates/deployment-revproxy.yaml
- helm-chart/renku-gateway/values.yaml
- internal/stickysessions/endpoints.go
- internal/stickysessions/endpoints_test.go
- internal/stickysessions/main.go
- pyproject.toml
/deploy #persist renku-core=develop renku=core-svc-horizontal-scaling renku-ui=update-renku-version-endpoint
New gateway release
> chore: prep 0.21.0 release

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
> chore: prep 0.21.1 release

- .github/workflows/acceptance-tests.yaml
- .github/workflows/ci.yml
> chore(ci): Update renku actions to v1.5.0

- app/__init__.py
- app/auth/oauth_redis.py
- app/tests/test_proxy.py
> fix: properly user Redis sentinel client

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
This is a small bugfix realse for the gateway.
> chore: prep 0.21.2 release

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
> chore: prep 0.21.3 release

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
New gateway release that supports cloud storage
> chore: prep 0.22.0 release

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
Updating the changelog for a new gateway release
> chore: prep 0.23.0 release

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
> chore: prep 0.23.1 release

- internal/revproxy/main.go
- internal/revproxy/main_test.go
Code from #703 was missing from the gateway refactor.
Also, added back a test case for search.
> fix: backport #703

- internal/login/login_server_routes.go
- internal/sessions/session_store.go
Fixes #724.
/deploy renku=release-0.57.1
> fix: save session more aggressively during login flows

- cmd/gateway/main.go
- internal/revproxy/main_test.go
- internal/revproxy/middlewares.go
> fix: update path rewrite

- internal/config/login_test.go
- internal/config/main.go
- internal/config/main_test.go
- internal/config/redacted_string.go
- internal/config/redacted_string_test.go
- internal/config/redis_test.go
- internal/config/revproxy_test.go
- internal/config/session_test.go
- internal/revproxy/main_test.go
- internal/revproxy/middlewares.go
Add some tests for the config of the gateway.
> chore: add tests for internal/config

- internal/revproxy/main.go
This allows the data service to easily add authentication for anonymous sessions.
> fix: pass cookies to data services

- internal/revproxy/main.go
- internal/stickysessions/main.go
> fix: do not stop the core svc LB watcher too soon

- .github/workflows/acceptance-tests.yaml
> ci: add cypress acceptance tests folder

- .github/workflows/acceptance-tests.yaml
> chore: modify CI pipeline to deploy to Azure
