- app/processors/gitlab_processor.py
Add special rule for path encoding to fix queries for base64 encoded repo files.
> Add another rule for URL encoded resource identifiers

- app/processors/gitlab_processor.py
Fix spaces in filenames by using a different method for url-encoding the filenames.
Closes #34
> Fix the URL-encoding of whitespace in filenames

- app/auth/web.py
- app/gateway/proxy.py
Send {'error': 'token_expired'} response on expired access_token.
Closes #39
> token_expired response

- run-telepresence.sh
Killing telepresence can leave the swapped k8s deployment broken. We therefore run a shell and manually start the dev server which can be killed followed by gracefully exiting telepresence.
> Manually start dev server inside telepresence

- app/processors/base_processor.py
- app/processors/gitlab_processor.py
Forward pagination headers in the response, modify URLs in the `Link` header such that they point to a gateway URL.
> Forward the pagination headers in the GitLab response

- app/blueprints/__init__.py
- app/processors/gitlab_processor.py
This is used to get meta-information about a repository file without transferring the entire file.
> Enable HEAD requests to gitlab.

- app/blueprints/webhooks.py
Use `Authorization: Bearer xxx` Instead of `OAUTH-TOKEN: xxx` for the authentication.
Fixes #107
> Authorize webhooks through bearer token

- app/__init__.py
- app/auth/gitlab_auth.py
- app/auth/jupyterhub_auth.py
- app/auth/keycloak_auth.py
- app/auth/web.py
- app/blueprints/graph.py
- app/config.py
- app/gateway/proxy.py
- app/processors/base_processor.py
- app/processors/gitlab_processor.py
- app/tests/test_proxy.py
- Remove side effects during imports
- Check for a keycloak public key before_request() if it is not part of the app context already
- Use standard quart app.logger everywhere except during module import
- Use warnings.warn() for warnings during import
This fixes the logging problems that have partially prevented logs from showing up in production.
Closes #106 and #98. A better logging strategy should be introduced later (see #113).
> Fix logging

- helm-chart/renku-gateway/templates/configmap.yaml
Change traefik config to enable access logs. Buffered (size 10) logs are written to stdout and thus picked up by k8s.
> Activate access logs in traefik

- helm-chart/renku-gateway/templates/configmap.yaml
The `ReplacePathRegex` middleware of traefik does not correctly handle URL-encoded paths. The problem is fixed by using the `StripPrefix` and `AddPrefix` middlewares instead.
Fixes #127.
> Fix forwarding of URL-encoded paths to gitlab

- helm-chart/renku-gateway/templates/configmap.yaml
Watching /config/traefik.toml (which is on per default) would be desirable as it would automatically pick up changes in the corresponding configmap. However, having file watching enabled currently breaks the deployments that are autmatically created as a part of the travis CI/CD pipeline on the main Renku repository.
So far, all other deployments seem to be ok with the watch = true setting though...
> Disable watching of the traefik config file

- app/auth/web.py
- app/tests/test_proxy.py
Federated identities can come with characters that are not supported as redis keys. Base 64 encoding those keys solves that issue.
> Base-64 encode redis keys

- helm-chart/renku-gateway/templates/configmap.yaml
* Add support for graph status API: SwissDataScienceCenter/renku-graph#69
* Change the incoming webhooks path to `/graph/webhooks/`
---
As we're doing a breaking change to the api here, do not merge this before the corresponding change in the UI is ready.
> support for graph endpoints

- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
Activating the development mode should not be done in production as it causes traefik to
- be more verbose
- be more generous on AllowedHosts, SSL and STS
> Configure a development mode for traefik

- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
Fix the traefik routing for gitlab for cases where gitlab is running under a different hosname instead of under the /gitlab path.
Note: This is a stripped down version of #142 that does not need any upstream chart changes. I tested it in our regular dev setup and in a minikube setup where Renku was deployed against gitlab.com.
Addresses #138 (fixes it for gitlab only)
> Fix traefik routing for gitlab

- app/config.py
- helm-chart/renku-gateway/Chart.yaml
- helm-chart/renku-gateway/templates/deployment.yaml
- helm-chart/renku-gateway/values.yaml
So far the use of a Keycloak realm called 'Renku' was hardcoded. This can now be set through the charts, the default is set at the application level to 'Renku'.
Closes #147
> feat: make Keycloak realm configurable

- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
- Restructure traefik configuration
- Introduce rate limits, make them configurable through chart values. The default chart values for the rate limits are 20 req per 10s (burstable up to 100 req / 10s) in general and 10 req per 3s (burstable up to 10 req / 10s) for the notebooks service. Violation of those limits will result in a `429 - too many requests` response.
---
The PR is currently deployed under https://andreas.dev.renku.ch
> Improve traefik settings

- helm-chart/renku-gateway/templates/configmap.yaml
These hardcoded helm variables accidentally added in the last PR were not used.
> fix(charts): remove accidentally added helm variables

- helm-chart/renku-gateway/values.yaml
I've added a typo when moving the tested configuration to the charts. Thanks for spotting it @lorenzo-cavazzi .
> fix(charts): fix typo in default values

- helm-chart/renku-gateway/values.yaml
When starting a new server, it's easy to hit the 10 requests per second burst threshold
> fix(charts): adjust notebooks rate limits

- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
We have recently raised the rate limits for requests to the notebooks service (#154) but it is occasionally reached when starting a new notebook with SwissDataScienceCenter/renku-ui#472 . Considering that SwissDataScienceCenter/renku-notebooks#177 has been merged, we can safely relax it a little bit more.
> fix(charts): re-adjust notebooks rate limits

- app/blueprints/graph.py
Using `dcterms` is no longer necessary and we are using `schema.org` instead - therefore the graph query needs to be modified.
> fix ontology definition

- helm-chart/renku-gateway/templates/configmap.yaml
This adds a temporary routing for the graphql endpoint -- must be fixed/improved but it's enough for a working solution.
Preview available at https://lorenzotest.dev.renku.ch
Requires SwissDataScienceCenter/renku-graph#88
> feat: add graphql routing in traefik

- Pipfile
- Pipfile.lock
pin chartpress version to avoid using the new charts naming convention
> build: fix chartpress version

- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
Deployed (together with #188) in https://andreas.dev.renku.ch
~Bumping to v2.0 only instead of v2.1 as tests (on a shaky network though) suggested some problems with v2.1. Leaving the upgrade to v2.1 (including some further tests) for later.~
Problem identified (https://github.com/containous/traefik/pull/5516) and fixed by explicitly turning host header forwarding off.
> chore: bump traefik version to v2.1.4

- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
closes #174.
Currently deployed under https://andreas.dev.renku.ch
> feat: add content-based redirection for Renku entities

- app/auth/jupyterhub_auth.py
- app/config.py
- helm-chart/renku-gateway/Chart.yaml
- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/templates/deployment.yaml
- helm-chart/renku-gateway/values.yaml
- Create a login route which triggers an anonymous session
with the secondary Jupyterhub instance handling temporary sessions.
Closes #193 
- Add rules to the gateway to separate traffic between
the primary and the secondary notebooks service.
Closes #195
> feat: enable anonymous jupyterhub sessions

- .travis/travis-functions.sh
The requirements lockfile has been removed from the main renku repo.
> ci: do not add requirements.lock to renku commit

- app/auth/gitlab_auth.py
- app/config.py
- app/templates/gitlab_logout.html
- helm-chart/renku-gateway/Chart.yaml
- helm-chart/renku-gateway/templates/deployment.yaml
- helm-chart/renku-gateway/values.yaml
GitLab 12.7.0 prevented triggering GitLab logout from outside GitLab, 12.9.0 brought it back. However, a POST request is necessary now. 
My(@ableuler) suggestion is actually to keep this PR open for 2-3 months until more people will be ready to migrate their GitLab instance to `>=12.9.0`.
> fix: change logout method to POST

- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
This PR removes the references to `core.fullname` and `knowledgeGraph.fullname` which are defined in the main renku chart. This allows the gateway chart to be rendered independently.
Closes #203.
> Remove dependency from renku chart

- Makefile
This changes the default make target from `tag` to `build` in order to fix the failing travis builds for the dependabot PRs (which contain slashes in their branch names that are not allowed to be used in docker tags).
> ci: change default make target to fix travis build

- chartpress.yaml
This allows to execute `pipenv run chartpress` through the pre commit hook.
> Move chartpress.yaml to repo root

- .travis/travis-deploy.sh
This was forgotten when moving the `chartpress.yaml` file to the repo root.
> Fix path in travis deploy step

- helm-chart/renku-gateway/templates/configmap.yaml
In SwissDataScienceCenter/renku-ui#905 we are going to use an undocumented API from GitLab, requiring to query directly `/gitlab` instead of `/gitlab/api/v4`.
This PR adds routing for `/api/direct/` to allow that interaction. It's necessary to split the "gitlab" middleware because it's not possible to have 2 `AddPrefix` middlewares where one adds a substring of the other.
P.S.
As a reference, this is the error we would get if we didn't split the middleware
```
time="2020-07-20T14:02:58Z" level=error msg="cannot create middleware: multi-types middleware not supported, consider declaring two different pieces of middleware instead" entryPointName=http routerName=direct@file
```
And this is an example of how the `AddPrefix` works with an old "gitlab" URL and a new "direct" URL
``` …
```
> chore: add direct route to gitlab to use undocumented apis

- helm-chart/renku-gateway/templates/configmap.yaml
The recent changes allowing to query non-api gitlab endpoints (https://github.com/SwissDataScienceCenter/renku-gateway/pull/251) introduced an error which manifests when gitlab is not running under `/gitlab`. This PR fixes it.
> fix(charts): fix a bug in the direct routing to gitlab

- .github/dependabot.yaml
~Together with merging this PR, the `dependabot preview` app should be deactivated for this repo~, see https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/.
We can merge this PR and see if it will result in dependency update PRs to the dedicated `dependabot-updates` branch. The idea would be to have auto-updates to a specific persistent branch and merge this branch into master occasionally.
> chore: move to github native dependabot

- app/auth/oauth_client.py
While trying to address #267 , I found a bug in the function checking the token expiration date.
This is very likely the reason for the unnecessary re-login triggered on the UI that happens frequently when polling a specific API for a long time, and occasionally in other situations.
***How to test***
This is a bit tricky. The easiest way is lowering the access token lifespan in your dev renkulab deplyoment to 1 minute (see the image below).
Then open any of your projects and go to the environment page, so that the `/servers` API will be invoked every ~3 seconds. Without this PR, the UI will trigger a full login and refresh every minute. Running this PR (thorugh telepresence or using the gateway-auth image `lorenzocavazzitech/renku-gateway:0.9.0-0a593a8`) the token should refresh …
> fix: adjust the time buffer in the token expiration date check function

- app/__init__.py
- run-telepresence.sh
The previous command to attach the VScode debugger didn't work because flask starts multiple sub-processes.
The `--no-reload` flag is the easiest fix, at the cost of dropping the auto-refresh when the code is changed. There may be other better solutions to explore (e.g. `debugpy`,  but I didn't manage to debug properly with that).
> docs: fix vscode debug command

- app/auth/web.py
- app/templates/redirect_logout.html
Perform all logouts in iframes on the same page. This simplifies the code, fixes the JupyterHub logout and the final logout redirection for deployments with external GitLab.
closes #314 and #191
> fix(app): fix JupyterHub logout and logout redirection

- app/auth/gitlab_auth.py
- app/auth/oauth_client.py
- app/auth/renku_auth.py
- app/auth/utils.py
- app/auth/web.py
This PR fixes obtaining the ID token from keycloak during login by making sure the defined scope is picked up by oauthlib (use `scope` instead of `scopes`) and ads the id token to a request which is forwarded to the core service in the custom header field `"Renku-User"` .
The original header fields are left there for backwards compatibility until the core service has adapted.
Closes #252
> feat(auth): pass on KC id token to core service

- app/__init__.py
This will
* Provide extra content to the UI when sending a 401 error related to expired/invalid tokens
* Handle an expected exception without logging the corresponding error
```
[2020-10-12 09:41:23,824] INFO in oauth_redis: Refreshing cache_656bba26-0863-4e12-9fbc-ec0f0e79a4e1_kc_oidc_client
[2020-10-12 09:41:23,970] WARNING in oauth_redis: Error refreshing tokens: invalid_grant Clearing client from redis.
[2020-10-12 09:41:23,975] WARNING in __init__: Error while authenticating request
Traceback (most recent call last):
File "/code/app/__init__.py", line 116, in auth
new_tokens = web.get_valid_token(headers)
File "/code/app/auth/web.py", line 97, in get_valid_token
return {"access_token": keycloak_oidc_client.access_token}
AttributeError: 'NoneType' object has no attribute …
```
> return verbose errors on token validation exceptions

- .github/workflows/acceptance-tests.yaml
- .github/workflows/ci.yml
- Update renku requirements only when a new version is released.
- Run ci deployements / acceptance tests against the main branch in renku.
closes #365.
> chore: adapt ci/cd logic

- app/auth/gitlab_auth.py
- helm-chart/renku-gateway/templates/configmap.yaml
This adds the `/api/kg` routing for the knowledge graph APIs. The GitLab token is added to the requests in the `Authorization` headers as `Bearer <gitlab-access-token>`
We can later remove the routes for `/graphql` since it's now accessible from `/kg/graphql` -- I'm delaying that to simplify merging the PR by not introducing braking changes.
This PR is already used in the test deployment https://lorenzotest.dev.renku.ch/
/deploy
fix #300
> feat: add routing for kg requests

- .github/workflows/acceptance-tests.yaml
Add the possibility to provide details to the `/ deploy` command.
Info: https://github.com/SwissDataScienceCenter/renku/pull/2073/files?short_path=e969017#diff-e969017621edbe724f851ca789090af791987d4a7386f2eb4ec5f85c58156baa
/deploy #notest renku-ui=0.11.8
> ci: enforce deploy string command

- app/__init__.py
- app/auth/notebook_auth.py
- helm-chart/renku-gateway/templates/configmap.yaml
This PR adds the header
`Renku-Gitlab-Accesstoken: <some-token>`
together with some other Renku specific header to authenticated requests to the notebooks service. Note that this is only a temporary solution as the expected header names / content will be synchronized between the different renku backend services.
/deploy
> feat: add renku headers to nb service requests

- app/__init__.py
- app/auth/notebook_auth.py
This adds an anonymous id `anon-id` to the cookie. The actual ID is added as `Renku-Auth-Anon-Id` header to notebook server requests, independent on wether the user is authenticated or not. 
caveats:
- once the UI server is ready, such a anonymous ID should be provided by the UI server
- for this to work properly, the UI needs to retry the very first AJAX request which sets the anonymous id in the cookie (a page reload will do as well until this is implemented).
/deploy
> feat(auth): add anonymous id to cookie

- helm-chart/renku-gateway/templates/configmap.yaml
The route `/api/direct` already exists to bypass the usual `/api/v4` prefix we add to queries going to GitLab.
The UI now requires access to GraphQL ( SwissDataScienceCenter/renku-ui#1529 ) .
We could use this rule, adding the GitLab access token when the user is authenticated.
/deploy
> Add GitLab auth to /direct endpoints

- .github/workflows/ci.yml
- helm-chart/renku-gateway/templates/_helpers.tpl
- helm-chart/renku-gateway/templates/deployment.yaml
- helm-chart/renku-gateway/values.yaml
So these `call-nested` helpers were meant (through some witchery) to call the template of a requirement/child helm chart and pull out the redis release name which is then used in the label to allow client applications to connect to redis.
Now since we rely on a global redis instance we should not use this anymore. There is no local redis anymore.
This was causing the helm chart building/publishing step to fail: https://github.com/SwissDataScienceCenter/renku-gateway/runs/5108179637?check_suite_focus=true
> fix(chart): fully remove parts of non-global redis

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
This includes only a fix for building the helm chart on top of `0.12.0`
> chore: prep 0.12.1 release

- helm-chart/renku-gateway/templates/_helpers.tpl
- helm-chart/renku-gateway/templates/deployment.yaml
0.12.1 cleaned up some of the helm chart templating but also unfortunately introduced a few bugs.
Not sure how the CI deployments in the PR that introduced these changes did not see this at all. I think that maybe there was an old pod that was successfully running and the new ones could never start to replace it so everything looked good.
> fix(chart): whitespace in helm templating

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
New release that fixes some issues introduced to the helm chart with the previous release
> chore: prep 0.12.2 release

- CHANGES.rst
- helm-chart/renku-gateway/Chart.yaml
New release for using global redis.
> chore: prep 0.13.0 release

- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
Doesn't do yet what it promises in the branch name (ie convert the toml to yaml) but it already cleans up the helm template for the traefik rules quite a bit and can thus be merged "as is". Note that #559 should be reviewed and merged first.
> refactor: clean up traefik rules

- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
This PR bumps traefik to the latest version. Since newer traefik versions treat all mistakes in configurations as errors, this PR also removes some misconfigured garbage that presumably never worked as intended. Also, to make debugging configuration errors a bit easier, the static configuration is split up into three files rather than one gigantic one.
> refactor: split up traefik rules and bump traefik version

- .github/workflows/ci.yml
Use the organization secrets instead of the repository ones (which will be removed).
> chore(ci) Fix correct env-var for Dockerhub authentication in CI action.

- helm-chart/renku-gateway/values.yaml
Some clarification in the values file how custom root CAs can be added to traefik.
> chore: document using self-signed certs in traefik

- helm-chart/renku-gateway/values.yaml
Just removed an unused part of the values file. Now that we have transitioned to the helm chart for traefik we do not need this section.
> chore(chart): remove unused values.yaml section

- Dockerfile
The docker image build is failing in other PRs with the message below. 
Using the latest pip version fixes it. We also do not need to have gcc installed in the image.
```
#9 19.82   EnvCommandError
#9 19.82 
#9 19.82   Command ['/usr/local/bin/python', '-m', 'pip', 'install', '--no-deps', '-U', '/root/.cache/pypoetry/artifacts/f0/1a/11/cae8bb8eb76eda6204ce3bc7cda0fe8da4565ac1df13a98d35513cea60/cryptography-37.0.2-cp36-abi3-manylinux_2_24_x86_64.whl'] errored with the following return code 1, and output: 
#9 19.82   ERROR: cryptography-37.0.2-cp36-abi3-manylinux_2_24_x86_64.whl is not a supported wheel on this platform.
#9 19.82   WARNING: You are using pip version 20.1.1; however, version 22.1.2 is available.
#9 19.82   You should consider upgrading via the '/usr/local/bin/python -m pip …
```
> fix(ci): docker image build

- helm-chart/renku-gateway/requirements.yaml
- helm-chart/renku-gateway/values.yaml
The latest certificates image and chart can run as non-root.
This is safer than what we had before.
Also the chart and image tags are not tracking each other. This is on purpose. 
> chore: run CA cert injection as non-root

- helm-chart/renku-gateway/templates/configmap.yaml
If external GitLab is used, redirect /gitlab to the external GitLab URL, including the trailing path content trailing if it exists.
This should be merged at the same time as SwissDataScienceCenter/renku#2741, which adds a rule to the standard Renku ingress to route traffic to /gitlab to renku-traefik if no Renku-bundled GitLab is deployed
> feat: redirect /gitlab to external GitLab url

- app/templates/redirect.html
- app/templates/redirect_logout.html
For some reason and setup in our routing navigating to `https://renku-ci-rp-3178.dev.renku.ch/api/auth/gitlab/login/` does not work and results in a 404. But if the trailing slash is removed then everything works.
It is funny because the meta tags and javascript do not contain the trailing slash and things work as expected. 
But if someone does not get redirected automatically and click the link then they will get a 404.
> fix: remove trailing slash from redirect links

- Dockerfile.traefik
- chartpress.yaml
- helm-chart/renku-gateway/templates/configmap.yaml
- helm-chart/renku-gateway/values.yaml
This is required for https://github.com/SwissDataScienceCenter/renku-python/pull/3178.
I created a really small and simple middleware plugin for traefik: https://github.com/SwissDataScienceCenter/cookiefilter. 
It follows the [traefik example](https://github.com/traefik/plugindemo) and [docs](https://plugins.traefik.io/create) on creating a custom plugin. This is required because the middlewares that come included in traefik cannot conditionally filter cookies. What we currently have in place (and the only thing remotely close to what we need) is [this](https://doc.traefik.io/traefik/middlewares/http/headers/) which simply can remove a specific header. So we currently use this middleware to remove all cookies but we cannot selectively keep some of them.
In order for sticky sessions to …
> feat: core service sticky sessions

- app/__init__.py
- app/auth/gitlab_auth.py
- app/auth/web.py
- app/config.py
- helm-chart/renku-gateway/templates/deployment.yaml
There is just too much stuff in the logs. Most of it is really not useful.
This should cut back a lot on the logs.
For example getting the logs from renkulab I see:
```
[2022-10-27 19:54:34,395] DEBUG in __init__: Discovered redis master at 10.42.10.193:6379
[2022-10-27 19:54:34,400] DEBUG in __init__: Discovered redis master at 10.42.10.193:6379
[2022-10-27 19:54:34,517] DEBUG in __init__: Discovered redis master at 10.42.10.193:6379
[2022-10-27 19:54:34,527] WARNING in web: The user does not have backend access tokens.
NoneType: None
[2022-10-27 19:54:35,290] DEBUG in __init__: Discovered redis master at 10.42.10.193:6379
[2022-10-27 19:54:35,299] WARNING in web: The user does not have backend access tokens.
NoneType: None
[2022-10-27 19:54:35,789] DEBUG in __init__: Discovered redis …
```
> chore: do not show debug logs

- app/auth/web.py
This enables the renku client to keep using refresh tokens even after a user logs out. This feature exactly for what we are using it. Doing data backups or similar operations even after the user has logged out but on their behalf.
See https://www.keycloak.org/docs/15.1/server_admin/index.html#_offline-access
> fix: use offline access tokens for renku client

- CHANGELOG.md
- cmd/revproxy/config.go
- cmd/revproxy/main.go
- go.mod
- helm-chart/renku-gateway/Chart.yaml
- helm-chart/renku-gateway/templates/deployment-revproxy.yaml
- helm-chart/renku-gateway/templates/pdb.yaml
- helm-chart/renku-gateway/values.yaml
- pyproject.toml
The first release of the gateway which does not use traefik as the reverse proxy.
I made sure the functionality around rate limits and things around scaling the app are setup properly. It seems that we have been ignoring the rate limits for a while now - most probably ever since we switched from using the traefik image to using the traefik helm chart.
Now the rate limits will be enforced and they will be enabled by default (as was originally intended). The value of the rate limits was set to 2 req/s (i.e. 20 requests / 10 seconds). I think this is too low so I kept the value of 20 which is 20 req/second. I think that 2 req/second is too low for some services like the ui-server.
EDIT: I removed the rate limiting by default because the ui server could potentially be blocked …
> chore: prep 0.19.0 release

- helm-chart/renku-gateway/templates/hpa-revproxy.yaml
- helm-chart/renku-gateway/values.yaml
The templating for the horizontal pod autoscaler was using a mix of apiVersion v1 and v2.
Now we use v2 and v2beta2 which are idential in terms of what we use from them and this covers any k8s version older than 1.12.
/deploy #persist extra-values=gateway.reverseProxy.autoscaling.enabled=true
> fix(chart): HPA for reverse proxy

- cmd/revproxy/main.go
- cmd/revproxy/main_test.go
As discussed with @lorenzo-cavazzi it will be nice to have all requests going to the KG and its components to go through the `/kg` route. 
Currently the `/api/projects` path leads to Gitlab most of the time except in a few specific cases when it goes to the kg. With the addition of the new path this is not the case anymore. This makes the pathing and logic easier to follow and it reduces the changes of errors.
> feat: add new /api/kg/webhooks path

- CHANGELOG.md
- helm-chart/renku-gateway/Chart.yaml
- pyproject.toml
New release including a new authenticated path for KG webhooks
> chore: prep 0.20.0 release

- helm-chart/renku-gateway/templates/deployment-revproxy.yaml
This causes the helm upgrade to fail because of the duplicate environment variable.
> fix(chart): duplicate env variable in revproxy

- cmd/revproxy/main.go
- cmd/revproxy/main_test.go
- cmd/revproxy/middlewares.go
closes https://github.com/SwissDataScienceCenter/renku-python/issues/3569
> fix: return 404 on wrong core svc metadata version

- cmd/revproxy/main.go
- cmd/revproxy/main_test.go
- cmd/revproxy/middlewares.go
The redirects for gitlab were originally implemented when we had traefik. When we migrated the redirect was not correctly setup. This should fix that.
> fix(proxy): properly redirect from /gitlab urls

- internal/stickysessions/endpoints.go
~This is just a draft, not ready for review yet.~
> fix(proxy): sticky sessions null dereference

- cmd/revproxy/config.go
- cmd/revproxy/main.go
- cmd/revproxy/main_test.go
Fixes #682.
Required by the ui.
> feat: add keycloak redirect

- cmd/revproxy/main.go
- cmd/revproxy/main_test.go
This is a breaking change it requires the search service and UI to adapt to it.
> feat!: do not strip 'api' from the search service path

- internal/revproxy/main.go
- internal/revproxy/main_test.go
Fixes #721.
/deploy #notest renku=release-0.57.0
> fix: inject renku access token for search

- .github/workflows/acceptance-tests.yaml
- internal/revproxy/auth.go
- internal/revproxy/main.go
- internal/revproxy/main_test.go
- internal/revproxy/middlewares.go
Also adds the anonymous user ID. All of this is required to be able to launch sessions with the new operator for the data service.
/deploy
> feat: add renku refresh token for data service

- cmd/gateway/main.go
- internal/config/config.yaml
- internal/config/main.go
Add support for enabling debug logs from the gateway.
/deploy #notest
With debug: `<slash>deploy #notest renku=leafty/gateway-debug-mode extra-values=gateway.debug=true`
> feat: debug mode

- internal/config/main_test.go
- internal/config/revproxy.go
- internal/config/revproxy_test.go
- internal/revproxy/main.go
- internal/revproxy/main_test.go
- internal/revproxy/middlewares.go
This routes all requests that go to the notebooks to the data service.
Tested the full suite of PRs for this in a separate PR on the renku repo. Also tested to make sure that sessions launched the old way still appear to anonymous and registered users.
> feat: replace notebooks with data service

- .github/workflows/acceptance-tests.yaml
* Run the Cypress acceptance tests for v2 and make legacy tests optional
* Phase out Selenium acceptance tests
* Add job names, cleanup unnecessary variables, and adjust a few details
/deploy
> ci: included changes to run v2 acceptance tests as made for v1.14.2

- cmd/gateway/main.go
- go.mod
- go.sum
- internal/config/main.go
- internal/config/other.go
- internal/login/login_server.go
- internal/login/login_server_routes.go
- internal/metrics/posthog.go
- internal/models/metrics.go
Test of this:
Note that the user id is the same for the posthog-python and posthog-go clients (data svc and gateway), so that all looks good
> feat: add login product metrics

- cmd/gateway/main.go
- internal/login/login_server_routes.go
Fixes an issue when no metric client is defined.
This is one of go's very tricky quirks: a uninitialized interface will check against `== nil`, but an interface initialized with the `nil` value will NOT check against `== nil`. See: https://dave.cheney.net/2017/08/09/typed-nils-in-go-2.
Fixes this issue:
```
[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine 263 [running]:
main.main.Recover.RecoverWithConfig.func25.1.1()
/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/middleware/recover.go:100 +0x150
panic({0x1af9a40?, 0x2f3ce60?})
/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/SwissDataScienceCenter/renku-gateway/internal/metrics.(*PosthogMetricsClient).UserLoggedIn(0x0, {0xc000906810?, 0xc0003b6460?})
/src/internal/metrics/posthog.go:21 …
```
> fix: do not crash the gateway when no metrics client is configured

- .github/workflows/ci.yml
This PR implements building and publishing images for both amd64 and arm64 architecture.
This make renku-gateway follow other packages such as renku-data-services that are available for both platforms.
> feat: create images for both amd64 and arm64
